package:
  name: openmembrane
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - molsysmt
  - pyunitwizard
  - openmm
  - nglview
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library... '
  dev_url: https://github.com/uibcdf/OpenMembrane
  doc_url: https://uibcdf.org/OpenMembrane
